import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)


Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [22]:
import numpy as np
list_ = ['1' ,'2' ,'3' ,'4' ,'5']
array_list = np.array(object = list_)

In [23]:

type(array_list)

numpy.ndarray

In [24]:
type(list_)

list

list_ datatype is showimg python ddata type list.
and array_list is numpy array

# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [29]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [30]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [31]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_ , dtype = int)

In [32]:
for i in list_:
    print(type(list_))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [33]:
for i in array_list:
    print(type(array_list))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [34]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [35]:
num_array.shape

(2, 3)

In [36]:
num_array.size

6

# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [38]:
import numpy as np
a = [[0,0,0] , [0,0,0] , [0,0,0]]
arr = np.array(a)

In [39]:
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [40]:
arr.size

9

In [41]:
arr.shape

(3, 3)

In [44]:
zero = np.zeros((3,3))

In [45]:
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [46]:
zero.size

9

In [47]:
zero.shape

(3, 3)

# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [50]:
import numpy as np
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])